version: 2.1

executors:
  salesforce-executor:
    docker:
      - image: node:18 # Use a stable Node.js version
    working_directory: ~/project

jobs:
  setup-scratch-org:
    executor: salesforce-executor
    steps:
      - checkout

      # Install the new Salesforce CLI correctly
      - run:
          name: "Install Salesforce CLI"
          command: |
            npm install --global @salesforce/cli
            echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
            echo 'export PATH=~/.local/share/sf/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            sf update
            sf --version  # Validate installation

      # Authenticate using the SFDX_URL from CircleCI Environment Variables
      - run:
          name: "Authenticate with Salesforce"
          command: |
            echo $SF_AUTH_URL > sfdx_auth.txt
            sf org login sfdx-url --sfdx-url-file sfdx_auth.txt --set-default-dev-hub
            sf org list

      # Create a new Scratch Org
      - run:
          name: "Create Scratch Org"
          command: sf org create scratch --definition-file config/project-scratch-def.json --set-default --duration-days 1 --alias ScratchOrg

      # Push metadata to Scratch Org
      - run:
          name: "Push Source to Scratch Org"
          command: sf project deploy start --source-dir force-app

      # Run Apex tests with Code Coverage
      - run:
          name: "Run Apex Tests"
          command: sf apex run test --code-coverage --result-format human

      # Delete the Scratch Org after tests (Cleanup)
      - run:
          name: "Delete Scratch Org"
          command: sf org delete scratch --target-org ScratchOrg --no-prompt

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - setup-scratch-org
